### ISSUE TITLE
Optionally serialize Options

### ISSUE THREAD

**Issue by pjenvey** [slog-rs/derive#5]
I think it's not uncommon for simple KV impls to skip serialization of Option fields completely when they're None.

Can slog_derive support this use case?

**Comment by Michael-F-Bryan** [comment]
I don't think we need to do anything to support this. The main slog crate has a `impl<V: Value> slog::Value for Option<V>` ([code]) which will serialize the item if it is `Some`, or do nothing if it is `None`.

[code]: https://github.com/slog-rs/slog/blob/61cebb3ee575e72f28c23e92d3e250322601d826/src/lib.rs#L2748-L2760

**Comment by nikclayton-dfinity** [comment]
I don't think this is quite right.

Consider the following:

```rust
#[derive(Clone, Debug, Default, Serialize, KV, SerdeValue)]
struct A {
    #[serde(skip_serializing_if = "Option::is_none")]
    b: Option<B>
}

#[derive(Clone, Debug, Default, Serialize, SerdeValue)]
struct B {
    #[serde(skip_serializing_if = "Option::is_none")]
    first: Option<String>,
    second: Option<String>
}

[...]

let a = A::default();
```


With (at least) `slog_json`, if I try and log that (`info!(logger, "msg"; a);`) I get the output

```
{
  "b": null
}
```

I would expect `{}` as the output.

If I partially construct `B` like this:

```
let a = A {
    b: Some(B {
        first: Some("hello world".into()),
        second: None,
    }),
};
```

and log `a` again I get:

```
{
   "b": {
     "first": "hello world"
   }
}
```

So skipping the option on the `second` field has worked.

If I remove the `KV` from the `derive` line, and write the log like `info!(logger, "msg"; "a" => a);` then the optional fields are correctly skipped, but everything is now under the "a" key in the output.
