### ISSUE TITLE
panicked at '`ToSendSerializer` can't fail: Other'

### ISSUE THREAD

**Issue by spearman** [slog-rs/derive#8]
This is the same program as #7, with erased-serde declared as a dependency so it will compile:

```
use serde::{Deserialize, Serialize};
use slog;
use sloggers;
use slog_derive::{KV, SerdeValue};

#[derive(Debug, Deserialize, Serialize, KV)]
struct Myrecord {
 pub a : String,
 pub b : B
}

#[derive(Clone, Debug, Deserialize, Serialize, SerdeValue)]
pub struct B {
  pub b : u8
}

fn main() {
  let log_root = {
    let mut builder = sloggers::terminal::TerminalLoggerBuilder::new();
    builder.level(sloggers::types::Severity::Debug);
    sloggers::Build::build (&builder).unwrap()
  };
  let myrec = Myrecord {
    a: "hello".to_string(),
    b: B { b: 5 }
  };
  slog::info!(log_root, ""; myrec);
}
```

Here is the full backtrace: https://gist.github.com/spearman/8da2b6912cf5090fe32bcd13e0c3fce7

**Comment by Michael-F-Bryan** [comment]
Looking through the backtrace I'm not sure this is related to `slog_derive`.

The panic seems to be triggered by [these lines](https://github.com/slog-rs/async/blob/465bfa926dcd866d0c7d1cebbfe43a53875f20a1/lib.rs#L462) in `slog-async`. I'm guessing when [implementing `Serializer` for `ToSendSerializer`](https://github.com/slog-rs/async/blob/465bfa926dcd866d0c7d1cebbfe43a53875f20a1/lib.rs#L89) they forgot to override something which returns an error by default.
